[package]
name = "rustc_restrictions"
version = "0.0.0"
edition = "2024"

[dependencies]
rustc_fluent_macro = { path = "../rustc_fluent_macro" }
rustc_errors = { path = "../rustc_errors" }
rustc_hir = { path = "../rustc_hir" }
rustc_macros = { path = "../rustc_macros" }
rustc_middle = { path = "../rustc_middle" }
rustc_span = { path = "../rustc_span" }
